site/api/urls.py
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from django.urls import path
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'regions', views.RegionViewSet)
router.register(r'departements', views.DepartementViewSet)
router.register(r'communes', views.CommuneViewSet)

urlpatterns  = router.urls
urlpatterns += [
    path('schema', get_schema_view(title='Geo API', version=1)),
    path('docs', get_swagger_view(title='Geo API'), name='docs')
]

site/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('geo.urls', namespace='geo'))
]

site/geo/urls.py
from django.urls import path
from . import views

app_name = 'geo'

urlpatterns = [
    path('', views.home, name="homepage"),
    path('communes/', views.commune_create, name="commune_create"),
    path('communes/<slug:code>/', views.commune_edit, name="commune_edit"),
]

site/geo/models.py
from django.db import models
from unidecode import unidecode
from .validators import validate_numeric

class Region(models.Model):
    code   = models.SlugField(max_length=2, primary_key=True, validators=[validate_numeric])
    nom    = models.CharField(max_length=32)

    def __str__(self):
        return self.code + ' ' + self.nom

class Departement(models.Model):
    code   = models.SlugField(max_length=3, primary_key=True, validators=[validate_numeric])
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    nom    = models.CharField(max_length=32)

    def __str__(self):
        return self.code + ' ' + self.nom

class Commune(models.Model):
    code        = models.SlugField(max_length=5, primary_key=True, validators=[validate_numeric])
    departement = models.ForeignKey(Departement, blank=True, null=True, on_delete=models.CASCADE)
    nom         = models.CharField(max_length=255)
    nom_norm    = models.CharField(max_length=255)
    population  = models.IntegerField()

    def __str__(self):
        return self.code + ' ' + self.nom

    @staticmethod
    def normalize(text):
        """
        Normalize the given text
        To be able to search on it efficiently (in DB)
        - replace accented letter with non-accented equivalent
        - replace hyphens with space
        - remove apostrophe
        - lowercase
        - add space at the beggining (to match the beggining of any word)

        :param string text
        :return string
        """
        if not text:
            return text

        text = unidecode(text)
        text = text.replace("-", " ")
        text = text.replace("'", "")
        return " " + text.lower().strip()

    def setCodesPostaux(self, codes, checkExisting=True):
        """
        :param set<string> codes
        :param boolean checkExisting - [True]
        """
        if checkExisting:
            for item in self.codepostal_set.all():
                if item.code in codes:
                    codes.remove(item.code)
                else:
                    item.delete()

        if codes:
            insert = []

            for cp in codes:
                insert.append(CodePostal(code=cp, commune=self))
            CodePostal.objects.bulk_create(insert, ignore_conflicts=True)

    def save(self, *args, **kwargs):
        self.nom_norm = self.normalize(self.nom)
        super().save(*args, **kwargs)

class CodePostal(models.Model):
    # Can be associated with several communes (ex 01330)
    id          = models.BigAutoField(auto_created=True, primary_key=True, verbose_name='ID')
    code        = models.CharField(max_length=5, db_index=True, validators=[validate_numeric])
    commune     = models.ForeignKey(Commune, on_delete=models.CASCADE)

    def __str__(self):
        return self.code

    class Meta:
        unique_together = (("code", "commune"),)

        verbose_name_plural = "Codes Postaux"

site/geo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Commune, CodePostal

class CommuneForm(forms.ModelForm):
    codesPostaux = forms.CharField(
                        required=False,
                        label='Codes postaux',
                        help_text='Liste séparée par des virgules')

    class Meta:
        model  = Commune
        fields = ('code', 'nom', 'population', 'departement', 'codesPostaux')


    def __init__(self, *args, **kwargs):
        """
        Tweak the view if we're editing an instance
        """
        super().__init__(*args, **kwargs)

        # We're editing an instance
        instance = getattr(self, 'instance', None)
        if instance and instance.code:
            self.fields['code'].disabled = True
            self.initial['codesPostaux'] = ",".join(sorted([str(x) for x in instance.codepostal_set.all()]))

    def clean_codesPostaux(self):
        """
        :raise ValidationError
        :return list
        """
        value = self.cleaned_data['codesPostaux'].strip()

        if not value:
            return value

        # Validate the codes
        f = CodePostal._meta.get_field('code')

        data = []
        for txt in value.split(","):
            if txt != "":
                f.clean(txt, None) # Raises ValidationError if invalid
                data.append(txt)

        return data

    def as_table(self):
        """
        Return this form rendered as HTML <tr>s
        -- excluding the <table></table>."
        """
        return self._html_output(
            normal_row='<tr%(html_class_attr)s><th>%(label)s</th><td>%(field)s%(help_text)s%(errors)s</td></tr>',
            error_row='<tr><td colspan="2">%s</td></tr>',
            row_ender='</td></tr>',
            help_text_html='<br><span class="helptext">%s</span>',
            errors_on_separate_row=False,
        )

site/geo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Commune, CodePostal
from .forms import CommuneForm

def home(request):
    return render(request, "geo/index.html", {})

def commune_create(request):
    if request.method == 'POST':

        # Save changes
        form = CommuneForm(request.POST)

        if form.is_valid():
            instance = form.save()
            instance.setCodesPostaux(set(form.cleaned_data['codesPostaux']), checkExisting=False)
            messages.success(request, 'La ville a bien été enregistrée.')

            return redirect('geo:commune_edit', code=instance.code)
    else:

        # Display form
        form = CommuneForm()

    return render(request, "geo/commune_form.html", {
        'form'    : form,
        'instance': False
    })

def commune_edit(request, code):
    instance = Commune.objects.get(code=code)

    if request.method == 'POST':

        # Delete
        if request.POST.get('delete'):
            instance.delete()
            messages.success(request, 'La ville "%s" a bien été supprimée.' % instance.nom)

            return redirect('geo:homepage')

        # Save changes
        else:
            form = CommuneForm(request.POST, instance=instance)
            if form.is_valid():
                instance = form.save()
                instance.setCodesPostaux(set(form.cleaned_data['codesPostaux']))
                messages.success(request, 'La ville a bien été enregistrée.')

                return redirect('geo:commune_edit', code=instance.code)
    else:

        # Display form
        form = CommuneForm(instance=instance)

    return render(request, "geo/commune_form.html", {
        'form'    : form,
        'instance': instance
    })

site/templates/geo/commune_form.html
{% extends 'base.html' %}

{% block content %}
<h1 class="header1">
  {% if instance %}Éditer "{{ instance.nom }}"{% else %}Créer une ville{% endif %}
</h1>

<form class="form" method="POST">
  {% csrf_token %}
  <table class="form-table">{{ form.as_table }}</table>

  <div class="actions">
    {% if instance %}
      <input type="hidden" name="delete" value="" />
      <button type="button" class="btn btn--default"
              onClick="if(confirm('Êtes-vous sûr de vouloir supprimer cette ville?')) {
                        this.previousElementSibling.value = '1'; this.form.submit() }">Supprimer</button>
    {% endif %}
    <button type="submit" class="btn btn--primary">Enregistrer</button>
  </div>
</form>
{% endblock content %}

site/templates/geo/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<a class="float-right" href="{% url 'geo:commune_create' %}">
  Ajouter
</a>
<h1 class="header1">
  Rechercher une ville
</h1>

<!-- SEARCH FORM -->
<form class="form" onSubmit="event.preventDefault(); search(this.elements.q.value)">
  <label class="sr-only" for="q">
    Code postal ou Nom
  </label>

  <div class="searchbar">
    <div class="searchbar-icon">
      <svg class="h-4 w-4 fill-current text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
      </svg>
    </div>
    <input id="q" name="q" type="search" class="searchbar-input"
           value="{{ request.GET.q }}" placeholder="Code postal ou Nom" autocomplete="off">
  </div>
</form>

<!-- RESULTS -->
<div id="results" class="mb-8"></div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
  const API_URL  = "{% url 'api:commune-list' %}";
  const EDIT_URL = "{% url 'geo:commune_edit' code='CODE' %}";
</script>
<script src="{% static 'js/geo.js' %}"></script>
{% endblock javascript %}