site/api/urls.py
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from django.urls import path
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'regions', views.RegionViewSet)
router.register(r'departements', views.DepartementViewSet)
router.register(r'communes', views.CommuneViewSet)

urlpatterns  = router.urls
urlpatterns += [
    path('schema', get_schema_view(title='Geo API', version=1)),
    path('docs', get_swagger_view(title='Geo API'), name='docs')
]

site/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('geo.urls', namespace='geo'))
]

site/geo/urls.py
from django.urls import path
from . import views

app_name = 'geo'

urlpatterns = [
    path('', views.home, name="homepage"),
    path('communes/', views.commune_create, name="commune_create"),
    path('communes/<slug:code>/', views.commune_edit, name="commune_edit"),
]

site/templates/base.html
<!DOCTYPE html>{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Geo API{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
  {% block head %}{% endblock head %}
</head>
<body>

<!-- HEADER -->
<header>
  <nav class="navbar navbar--primary">
    <div class="navbar-brand"><a href="{% url 'geo:homepage' %}">Geo</a></div>
    <div class="navbar-nav">
      {% block navbar %}<a class="nav-link" href="{% url 'api:docs' %}">API Docs</a>{% endblock navbar %}
    </div>
  </nav>
</header>

<!-- MAIN -->
<main class="container mx-auto pt-5">
  <noscript>
    <div class="alert alert--error mb-8">Ce site nécessite JavaScript.</div>
  </noscript>

  {% if messages %}
  <ul class="mb-4">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert--{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% block content %}{% endblock content %}
</main>

{% block javascript %}{% endblock javascript %}
</body>
</html>